version: "3.7"

services:
  #######################################
  # Insomnia: Openapi 2 kong declarative
  #######################################
  generate-kong-configs:
    image: kong/inso:latest
    working_dir: /app
    volumes:
      - .:/app
    command:
      generate config api-with-example.yaml --output ./compose/kong/declarative/kong.yml --type declarative --verbose --tags api-example-v2

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    container_name: kong
    build:
      dockerfile: kong-with-plugin.Dockerfile
      context: compose

    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: warn
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 120s
      timeout: 10s
      retries: 3
    volumes:
      - ./compose/kong/logs:/usr/local/kong/logs
      - ./compose/kong/logs/log.txt:/usr/local/kong/logs/log.txt
      - ./compose/kong/declarative:/usr/local/kong/declarative
      # - ./compose/kong/config/nginx.conf:/usr/local/kong/nginx.conf
      # - ./compose/kong/config/nginx-kong.conf:/usr/local/kong/nginx-kong.conf
    ports:
      - "8001:8001"
      - "8444:8444"
      - "8000:8000"
      - "8443:8443"
      - "9080:9080"
      - "9081:9081"
