openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
servers:
  - url: http://simple-api-server:4000/
    description: api-example-v2
paths:
  /api/v2/users:
    get:
      operationId: getUsersDetailsV2
      summary: Show users details
      responses:
        '200':
          description: |-
            200 response
      x-kong-plugin-google-recaptcha:
        name: google-recaptcha
        enabled: true
        config:
          site_key: 'this_is_a_site_key_from_google'
          secret_key: 'this_is_a_site_secret_from_google'
    post:
      operationId: creatNewUserV2
      summary: create a new user
      responses:
        '201':
          description: |-
            201 response
      x-kong-plugin-google-recaptcha:
        name: google-recaptcha
        enabled: true
        config:
          site_key: 'this_is_a_site_key_from_google'
          secret_key: 'this_is_a_site_secret_from_google'
