openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
servers:
  - url: http://simple-api-server:4000/
    description: api-example-v2
paths:
  /api/v2/users:
    get:
      operationId: getVersionDetailsv2
      summary: Show API version details
      responses:
        '200':
          description: |-
            200 response
